<?php

use Illuminate\Database\Seeder;
use App\Chapter;

class ChaptersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
         Chapter::insert([
        	['objective' => 'This is a seeded objective.',
        		'discussion' => 'This is a seeded discussion.',
        		'example' => 'This is a seeded example',
        		'guided_practice' => 'This is a seeded guided_practice',
        		'tip' => 'This is a seeded tip.',
        		'key_point' => 'This is a seeded key point.',
        		'topic_id' => 1,
        		'created_at' => NULL, 
        		'updated_at' => NULL],
             ['objective' => 'This is a seeded objective.',
                 'discussion' => 'This is a seeded discussion.',
                 'example' => 'This is a seeded example',
                 'guided_practice' => 'This is a seeded guided_practice',
                 'tip' => 'This is a seeded tip.',
                 'key_point' => 'This is a seeded key point.',
                 'topic_id' => 2,
                 'created_at' => NULL,
                 'updated_at' => NULL],
             ['objective' => 'This is a seeded objective.',
                 'discussion' => 'This is a seeded discussion.',
                 'example' => 'This is a seeded example',
                 'guided_practice' => 'This is a seeded guided_practice',
                 'tip' => 'This is a seeded tip.',
                 'key_point' => 'This is a seeded key point.',
                 'topic_id' => 3,
                 'created_at' => NULL,
                 'updated_at' => NULL],
             ['objective' => 'This is a seeded objective.',
                 'discussion' => 'This is a seeded discussion.',
                 'example' => 'This is a seeded example',
                 'guided_practice' => 'This is a seeded guided_practice',
                 'tip' => 'This is a seeded tip.',
                 'key_point' => 'This is a seeded key point.',
                 'topic_id' => 4,
                 'created_at' => NULL,
                 'updated_at' => NULL],
             ['objective' => 'This is a seeded objective.',
                 'discussion' => 'This is a seeded discussion.',
                 'example' => 'This is a seeded example',
                 'guided_practice' => 'This is a seeded guided_practice',
                 'tip' => 'This is a seeded tip.',
                 'key_point' => 'This is a seeded key point.',
                 'topic_id' => 5,
                 'created_at' => NULL,
                 'updated_at' => NULL],
             ['objective' => 'This is a seeded objective.',
                 'discussion' => 'This is a seeded discussion.',
                 'example' => 'This is a seeded example',
                 'guided_practice' => 'This is a seeded guided_practice',
                 'tip' => 'This is a seeded tip.',
                 'key_point' => 'This is a seeded key point.',
                 'topic_id' => 6,
                 'created_at' => NULL,
                 'updated_at' => NULL],
             ['objective' => 'This is a seeded objective.',
                 'discussion' => 'This is a seeded discussion.',
                 'example' => 'This is a seeded example',
                 'guided_practice' => 'This is a seeded guided_practice',
                 'tip' => 'This is a seeded tip.',
                 'key_point' => 'This is a seeded key point.',
                 'topic_id' => 7,
                 'created_at' => NULL,
                 'updated_at' => NULL],
             ['objective' => 'This is a seeded objective.',
                 'discussion' => 'This is a seeded discussion.',
                 'example' => 'This is a seeded example',
                 'guided_practice' => 'This is a seeded guided_practice',
                 'tip' => 'This is a seeded tip.',
                 'key_point' => 'This is a seeded key point.',
                 'topic_id' => 8,
                 'created_at' => NULL,
                 'updated_at' => NULL],
             ['objective' => 'This is a seeded objective.',
                 'discussion' => 'This is a seeded discussion.',
                 'example' => 'This is a seeded example',
                 'guided_practice' => 'This is a seeded guided_practice',
                 'tip' => 'This is a seeded tip.',
                 'key_point' => 'This is a seeded key point.',
                 'topic_id' => 9,
                 'created_at' => NULL,
                 'updated_at' => NULL],
             ['objective' => 'This is a seeded objective.',
                 'discussion' => 'This is a seeded discussion.',
                 'example' => 'This is a seeded example',
                 'guided_practice' => 'This is a seeded guided_practice',
                 'tip' => 'This is a seeded tip.',
                 'key_point' => 'This is a seeded key point.',
                 'topic_id' => 10,
                 'created_at' => NULL,
                 'updated_at' => NULL]
        ]);
    }
}


